### ISSUE TITLE
Google Play Crush Report Google Analytics Version 3.02 java.lang.NullPointerException

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gzog/analytics-issues#451]
```
My application uses Google Analytics Version 3.02

Google Play Crush Report

26.06.2014
23:59
Android 2.3.3 - 2.3.7
Galaxy Ace (GT-S5830i)

java.lang.NullPointerException
at android.app.ContextImpl.openFileOutput(ContextImpl.java:432)
at android.content.ContextWrapper.openFileOutput(ContextWrapper.java:158)
at 
com.google.analytics.tracking.android.ClientIdDefaultProvider.storeClientId(Clie
ntIdDefaultProvider.java:102)
at 
com.google.analytics.tracking.android.ClientIdDefaultProvider.generateClientId(C
lientIdDefaultProvider.java:123)
at 
com.google.analytics.tracking.android.ClientIdDefaultProvider.initializeClientId
(ClientIdDefaultProvider.java:179)
at 
com.google.analytics.tracking.android.ClientIdDefaultProvider$1.run(ClientIdDefa
ultProvider.java:134)
```

Original issue reported on code.google.com by `mobildev...@gmail.com` on 27 Jun 2014 at 6:56

**Comment by GoogleCodeExporter** [comment]
Original comment by `pfrise...@google.com` on 10 Oct 2014 at 6:23
- Added labels: **Component-MobileTracking**, **Library-Android**
- Removed labels: **Component-CoreReportingAPI**

**Comment by GoogleCodeExporter** [comment]
```
I have the same BUG

java.lang.NullPointerException
at android.app.ContextImpl.openFileOutput(ContextImpl.java:442)
at android.content.ContextWrapper.openFileOutput(ContextWrapper.java:158)
at 
com.google.analytics.tracking.android.ClientIdDefaultProvider.storeClientId(Clie
ntIdDefaultProvider.java:102)
at 
com.google.analytics.tracking.android.ClientIdDefaultProvider.generateClientId(C
lientIdDefaultProvider.java:123)
at 
com.google.analytics.tracking.android.ClientIdDefaultProvider.initializeClientId
(ClientIdDefaultProvider.java:179)
at 
com.google.analytics.tracking.android.ClientIdDefaultProvider$1.run(ClientIdDefa
ultProvider.java:134)

see attached file below

```

Original comment by `kobozevalexander@gmail.com` on 21 Oct 2014 at 7:52

Attachments:
- [sdkbug.jpg](https://storage.googleapis.com/google-code-attachments/analytics-issues/issue-451/comment-2/sdkbug.jpg)

**Comment by GoogleCodeExporter** [comment]
```
Update your SDK and close this issue.
```

Original comment by `jaredsburrows@gmail.com` on 11 Feb 2015 at 12:54

**Comment by GoogleCodeExporter** [comment]
Original comment by `pfrise...@google.com` on 20 Mar 2015 at 9:18
- Changed state: **Obsolete**

**Comment by GoogleCodeExporter** [comment]
```
Hi, What is the solution? Only downgrading google play services to version 
2.3.43?
```

Original comment by `WillyEst...@gmail.com` on 20 Mar 2015 at 9:27
