### ISSUE TITLE
Error on Data Pull from Google Core API V3 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gzog/analytics-issues#814]
```
Team, 

We are using Core Reporting V3 API in C# to get the data from Google Analytical 
data into SQL Server. 

We have been using this service for last 5 months, we have got the below issue 
2 times, but after we re-run the package it works fine. Looks like we are 
pulling the data when your team is loading the data, but not sure. Could you 
please assist on this issue? Thanks !

TblGAGeoQuery_Tbl2   Error Code :-1073450910 Error : The service analytics has 
thrown an exception: Google.GoogleApiException: 
Google.Apis.Requests.RequestError
No such dimension(s): ga:dimension2
No such metric(s): ga:goal3Completions, ga:goal9Completions, 
ga:goal10Completions, ga:goal2Completions, ga:goal14Completions, 
ga:goal13Completions [400]
Errors [
    Message[No such dimension(s): ga:dimension2
No such metric(s): ga:goal3Completions, ga:goal9Completions, 
ga:goal10Completions, ga:goal2Completions, ga:goal14Completions, 
ga:goal13Completions] Location[ - ] Reason[badRequest] Domain[global]
]

   at Microsoft.SqlServer.Dts.Pipeline.ScriptComponentHost.HandleUserException(Exception e)
   at Microsoft.SqlServer.Dts.Pipeline.ScriptComponentHost.PrimeOutput(Int32 outputs, Int32[] outputIDs, PipelineBuffer[] buffers)
   at Microsoft.SqlServer.Dts.Pipeline.ManagedComponentHost.HostPrimeOutput(IDTSManagedComponentWrapper100 wrapper, Int32 outputs, Int32[] outputIDs, IDTSBuffer100[] buffers, IntPtr ppBufferWirePacket)   STDWSQL-CDS\CDS




Thanks,
Senthil

---------------------------------------------------------------------------
NOTE: This tool is not designed to request help. It is only for reporting
issues and requesting features for the Google Analytics libraries.

If you are a developer and you need help, visit:
https://developers.google.com/analytics/help/

If you are not a developer and you need help, visit:
https://support.google.com/analytics
---------------------------------------------------------------------------
Name of affected component: Core Reporting API

Name of related library and version, if applicable (e.g. Java, Python,
HTTP, Objective-C, etc.):

Issue summary:
Provide a brief summary of the issue you're experiencing.

Steps to reproduce issue:
1.
2.
3.

Expected output:
What do you expect to see after performing the above steps?

Actual results:
What do you actually see after performing the above steps?

Notes:
Provide any additional information which might be useful here. Feel free to
attach screenshots or sample code which demonstrates the issue being
described.

```

Original issue reported on code.google.com by `Senthil....@gmail.com` on 11 Dec 2015 at 2:33

**Comment by GoogleCodeExporter** [comment]
```
Is this a persistent error or was it just a one time error? Can you reproduce 
this error within the query explorer: 
https://ga-dev-tools.appspot.com/query-explorer/
```

Original comment by `mcoh...@google.com` on 11 Dec 2015 at 3:57

**Comment by GoogleCodeExporter** [comment]
```
This happened after the job has run 785 times, got this error 2 times out of 
785 times. 

Re-starting the job, fixes the issue. Not sure how I can replicate in Query 
Explorer.  
```

Original comment by `Senthil....@gmail.com` on 11 Dec 2015 at 4:10

**Comment by GoogleCodeExporter** [comment]
```
Team,

I have tried the same query in Query Explorer multiple times, it passed and got 
the results. Same thing happen when we run the C# code, first time it failed 
with the above error, re-run of the same code passed and got the results. 

Can you also let us know what are the timings the data get loaded on your end? 
May be we are pulling the data when you are loading it on Google Analytical 
Services. 


```

Original comment by `Senthil....@gmail.com` on 14 Dec 2015 at 3:06

**Comment by GoogleCodeExporter** [comment]
```
Team, 

Could you please assist on this issue ? We are having a Production Issue need 
to fix.

Thanks
Senthil
```

Original comment by `Senthil....@gmail.com` on 17 Dec 2015 at 7:11

**Comment by GoogleCodeExporter** [comment]
```
Team, 

Could you please share if there are any resolution on this issue?? Thanks 
```

Original comment by `Senthil....@gmail.com` on 8 Jan 2016 at 3:19
